version: '3'

services:
  app:
    image: graphene_django_helpers/tests
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    command: pytest
    ports:
      - '8000:8000'
    volumes:
      - ../..:/src
